{
  "comments": [
    {
      "key": {
        "uuid": "da33351e_e37ecfe3",
        "filename": "service/st-app-fw/src/st_cloud_manager.c",
        "patchSetId": 2
      },
      "lineNbr": 195,
      "author": {
        "id": 13
      },
      "writtenOn": "2018-07-23T09:58:38Z",
      "side": 1,
      "message": "if retry is tried on sign_up step, what happen in cloud_start_process()?",
      "range": {
        "startLine": 194,
        "startChar": 0,
        "endLine": 195,
        "endChar": 31
      },
      "revId": "738dd015e1e1dfcae941d5a9f5e000c1e7696bc8",
      "serverId": "c6509b8a-a471-4ec1-8e5f-9aed2654acb5",
      "unresolved": false
    }
  ]
}